//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchitectureWebSite_ASP.NET.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesignAgency
    {
        public int DesignAgencyID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string Creativity { get; set; }
        public string Management { get; set; }
        public string SpacePlan { get; set; }
        public string Image { get; set; }
    }
}
