//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchitectureWebSite_ASP.NET.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testimonials
    {
        public int TestimonialsID { get; set; }
        public string Comment { get; set; }
        public string Location { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateTestimonial { get; set; }
    }
}
