//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchitectureProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class About
    {
        public int AboutID { get; set; }
        public string BigTitle { get; set; }
        public string SubTitle { get; set; }
        public string Content { get; set; }
        public string OurStory { get; set; }
        public string OurGoal { get; set; }
        public string BigImage { get; set; }
        public string ShortImage { get; set; }
    }
}
