//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchitectureProject.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArchitectureDbEntities : DbContext
    {
        public ArchitectureDbEntities()
            : base("name=ArchitectureDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About> About { get; set; }
        public virtual DbSet<Blog> Blog { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<DesignAgency> DesignAgency { get; set; }
        public virtual DbSet<Portfolio> Portfolio { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<SiteSettings> SiteSettings { get; set; }
        public virtual DbSet<Slider> Slider { get; set; }
        public virtual DbSet<Statistic> Statistic { get; set; }
        public virtual DbSet<Team> Team { get; set; }
        public virtual DbSet<Testimonials> Testimonials { get; set; }
    }
}
