//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchitectureProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portfolio
    {
        public int PortfolioID { get; set; }
        public string Image { get; set; }
        public string Title { get; set; }
        public string ProjectType { get; set; }
        public string CustomerSupport { get; set; }
        public string Clients { get; set; }
        public string Location { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> DatePortfolio { get; set; }
    }
}
