//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchitectureProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteSettings
    {
        public int SiteSettingsID { get; set; }
        public string FacebookLink { get; set; }
        public string LinkedinLink { get; set; }
        public string InstagramLink { get; set; }
        public string TwitterLink { get; set; }
        public string YoutubeLink { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string CompanyNumber { get; set; }
        public string Email { get; set; }
        public string Map { get; set; }
    }
}
