//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchitectureProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int TeamID { get; set; }
        public string Name { get; set; }
        public string Job { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> DateTeam { get; set; }
        public string ShortContent { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
